POST http://localhost:8082/cliente HTTP/1.1
content-type: application/json

{
    "name": "Carlos Perez",
    "lastName": "Gonzalez",
    "email": "a@gmail.Content-MD5: ",
    "phone": "9996366333"
}


###
GET  http://localhost:8081/cliente/2 HTTP/1.1
content-type: application/json

###
PUT http://localhost:8080/cliente HTTP/1.1
content-type: application/json

{
    "name": "Carlos",
    "lastName": "Gonzalez",
    "email": "a@gmail.Content-MD5: ",
    "phone": "9996366333"
}

###
DELETE   http://localhost:8080/cliente/1 HTTP/1.1
content-type: application/json


